import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anurag_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-x-hidden text-white relative bg-black overflow-y-auto scrollbar-hidden`}
      >
        {/* 🔴 Stable red-orange radial gradients (no animation) */}
        <div className="absolute inset-0 z-[-3] bg-black">
          <div className="absolute top-[-30%] left-1/2 -translate-x-1/2 h-[500px] w-[500px] rounded-full bg-[radial-gradient(closest-side,_#D71F26,_#FF7B1C,_#000)] blur-[100px] opacity-80" />
          <div className="absolute top-[20%] left-[60%] h-[250px] w-[250px] rounded-full bg-[radial-gradient(closest-side,_#FF7B1C,_#000)] blur-[80px] opacity-30" />
        </div>

        {children}
      </body>
    </html>
  );
}
